### ISSUE TITLE
Get Stickers

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/budgetparty#104]
<img width="507" alt="screen shot 2017-05-10 at 8 58 52 pm" src="https://cloud.githubusercontent.com/assets/10767430/25928763/8c13e57a-35c3-11e7-8265-c37742bbfafb.png">

@brainnews is it okay if we change the icons circled in red to match the style of the icons circled in green before we get stickers?

**Comment by brainnews** [comment]
@VictoriaODell Sure! Do you need me to do it? Or is someone else on it? I'm happy to do it, just wasn't clear from your comment above whether or not you need my help.

**Comment by VictoriaODell** [comment]
@miles It would be great if you could do it. I didn't want to make any changes without checking in with you. :)

**Comment by brainnews** [comment]
on it!

**Comment by brainnews** [comment]
here's the updated logo:

![bp-logo](https://cloud.githubusercontent.com/assets/3944802/26035497/96775052-3892-11e7-920e-cfdb99d847b1.png)

**Comment by VictoriaODell** [comment]
yay! thanks @brainnews

**Comment by mateoclarke** [comment]
@briannews, can you upload an SVG too?

**Comment by brainnews** [comment]
SVG: 
[bp-logo.svg.zip](https://github.com/open-austin/budgetparty/files/1000122/bp-logo.svg.zip)

**Comment by VictoriaODell** [comment]
stickers ordered.
