### ISSUE TITLE
New Domain name? 

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/budgetparty#105]
Austinbudget.party is what we currently have but we should think about getting a domain name that doesnt have a specific city name in it. 

We considered austin.budgetparty.?

Still a work in progress

**Comment by mateoclarke** [comment]
- budgetparty.city
- budgetparty.org
- budgetparty.us
- budgetparty.net
- budgetparty.xyz
- budgetparty.tech
- budgetparty.party 😂

**Comment by mateoclarke** [comment]
I got budgetparty.org registered for 5 years. This will allow us to subdomain at austin.budgetparty.org, etc etc.

Will close this, but make a new issue to establish that in the future.
