### ISSUE TITLE
Bug: when attempting to submit in the Explain Your Spending view, the program fails

### ISSUE THREAD

**Issue by gness1804** [open-austin/budgetparty#118]
Apparently an error with bad prop type (see screenshot).
The program fails when user clicks on the "done" button.

<img width="1280" alt="screen shot 2017-05-12 at 4 58 44 pm" src="https://cloud.githubusercontent.com/assets/17103851/26018449/a317c10c-3734-11e7-8e97-8f143b375ab8.png">

**Comment by mateoclarke** [comment]
This is tricky. I'm having a hard time replicating this consistently. I have seen it before but I'm not seeing it now. 🙃
