### ISSUE TITLE
Update to use new logo

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/budgetparty#129]
We need to update the logo [on the homepage](http://austinbudget.party/login):
![image](https://cloud.githubusercontent.com/assets/10767430/26714059/3d24cfbe-4735-11e7-8002-fbe6aaddfdbc.png)

Here is the image to replace it with. 
https://github.com/open-austin/budgetparty/files/1000122/bp-logo.svg.zip

**Comment by VictoriaODell** [comment]
This is a better version of the logo. The : 
https://drive.google.com/open?id=0BwKb2oghmQldOXd6eldIQV9majA

**Comment by VictoriaODell** [comment]
@cdikibo lmk if you have any trouble with the file or anything!

**Comment by cdikibo** [comment]
There's a pull request

**Comment by mateoclarke** [comment]
Hey @VictoriaODell, looks like there is a white bar that runs through the new logo. Is that meant to be there?

<img width="1552" alt="screen shot 2017-06-27 at 2 34 19 am" src="https://user-images.githubusercontent.com/5697474/27576033-4255a7b4-5ae1-11e7-821e-35f2298a73a6.png">

**Comment by VictoriaODell** [comment]
No. I saw that too and I thought I uploaded a clean version in my latest
post in the issue but possible I just uploaded a dupe.

**Comment by mateoclarke** [comment]
ok, i'll try to clean the logo up, unless you have a clean version you can share?

**Comment by mateoclarke** [comment]
https://github.com/open-austin/budgetparty/commit/ae9807b85b94a39619d9523789b7a61d7b171c9f

<img width="1552" alt="screen shot 2017-06-27 at 12 52 10 pm" src="https://user-images.githubusercontent.com/5697474/27602238-b9385574-5b37-11e7-8c1c-3dde3d5afa93.png">

**Comment by VictoriaODell** [comment]
ty. Sorry busy right now. It looks like I just deleted over the changes I made when I was cleaning/organzing my files. 😭 I just spilled water on my continuum computer too. #NotMyDay
