### ISSUE TITLE
Feedback from Amy Stansbury (Austin Eco Network/Civics 101)

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/budgetparty#147]
- Some kind of way that you get feedback in a personal sense. How spending more on services relates to your personal tax rate and fees you pay.
- Some way you can start from scratch. have a fixed general fund amount. Dedicate the percent you think each dept should get as a percent.
- How does this get back to Council Members and to City Budget Office, City Manager Staff. Collect a user's zip code and council district.
- The many places that property taxes come from. It is fundamentally untrue that all your property taxes go to the City, it also goes to the school district, County, ACC, Central Health. Only 20% goes to the City.

**Comment by VictoriaODell** [comment]
Moved feedback to a feedback folder in our drive: https://drive.google.com/open?id=0BwKb2oghmQldc1BFZHJpc0UxVE0
