### ISSUE TITLE
Develop marketing landing page

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/budgetparty#165]
https://github.com/open-austin/budgetparty-landing

**Comment by VictoriaODell** [comment]
I'll try to add everything needed for this tonight at the hack night! @prestonp will be helping out with this. 

Empty repo here: https://github.com/open-austin/budgetparty-landing

**Comment by prestonp** [comment]
@mateoclarke I just poked around the budgetparty main repo. I saw it's built in react, what if I made the landing page a node package, that you could just npm install and plug in for the root route.

```
npm install --save-dev budgetparty-landing
```

```
import Landing from 'budgetparty-landing'

...

render() {
  <Landing/>
}
```

**Comment by mateoclarke** [comment]
That sounds spiffy! Before you do that, I'd want to take a step back and pose this question to @VictoriaODell too.

Where should the landing page live Vickie? Should it replace the app and be at the URL `austinbudget.party`? If so, what URL would the app live at? Or did we want to purchase a different domain (re: #105)?

More options: We could have it hosted as a subdomain at something like `about.austinbudget.party`. Or it could be at a subdirectory, like `austinbudget.party/about`.

@prestonp, if we go with the subdirectory option, the node package method you suggested would work too with React Router.

**Comment by mateoclarke** [comment]
@VictoriaODell and I talked about this tonight. We think it makes sense to go ahead and have the landing page live at austinbudget.party. And Vickie said she would work on updating the design assets to make the main call to action "Login" or "Join the Party" or whatever. 

Currently, when you go to austinbudget.party, you either get redirected to `/login` if you aren't authed, or `/dashboard` if you are. So making that module  like you suggested @prestonp sounds 👍

**Comment by VictoriaODell** [comment]
I made some updates, a mobile view of the landing page, and added a little style reference sheet thing. The most recent version is in this folder here: https://drive.google.com/open?id=0BwKb2oghmQldYXU3LXdWVG9fcFE

@prestonp can you review and lmk if you have any questions or if anything is off/weird? I've been working on this for a little while so my eyes are a little crossed 😵  If all's good I'll start to save out assets. 

I think we can move to the other repo from here, yeah?

TY.

**Comment by prestonp** [comment]
Maybe I should inline the components into this project. There's not a whole lot of markup and I think trying to isolate all the styling is a lot harder than it has to be.

**Comment by VictoriaODell** [comment]
@prestonp can we sync on this later tonight or tomorrow? It would be nice if we could just the homepage working for desktop and mobile up by Tuesday.

**Comment by prestonp** [comment]
@VictoriaODell Yes! I should be able to submit a pull req to the main repo tonight.

**Comment by mateoclarke** [comment]
Think there are a couple outstanding issues to get this working 💯  but those are captured separately. Let's call this issue donzo and 👏  for @VictoriaODell & @prestonp for leading this!!!

https://github.com/open-austin/budgetparty-landing/issues/7
https://github.com/open-austin/budgetparty-landing/issues/6
