### ISSUE TITLE
Talking Points/Packet to Council Members

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/budgetparty#168]
@danielryne => 
  @mateoclarke + @VictoriaODell  =>
    👀 from David Edmonson, ATA + Glasshouse Policy

**Comment by danielryne** [comment]
Hey @mscarey, @mateoclarke and @VictoriaODell - do you all have any previous literature on (1) the city's budgeting tool and/or (2) how the budget party app came to be? Even grant language would be helpful.

**Comment by mateoclarke** [comment]
@graceatkins did some research when she was working with Glasshouse. She was going to look back through stuff for us.

**Comment by danielryne** [comment]
Amazing! Thank you, @graceatkins ! Please let me know what you find. I'm setting aside time on Friday + Saturday to work on this, fyi.

**Comment by mateoclarke** [comment]
Posting what @graceatkins shared with me via email...

The [presentation](https://docs.google.com/presentation/d/1LNpQKPLYamcLcbLTU_n82qRD5sS6HrIOjMrgrfoUvBg/edit?usp=sharing) she did at a Open Gov & Civic Tech meetup (quick summary of differences between platforms and benefits of a better designed one) 

There are two quick overviews about  [Austin Energy](https://docs.google.com/document/d/1rM3Y7c700IZL_aiTlqtpQ7KzbhjIN2JeSYBB_kmeBms/edit?usp=sharing) and [Austin Transportation](https://docs.google.com/document/d/1xLrcV0AMtR5aBdZvnrQ7ri3q4_BBGoRWPyWqqJXLKJk/edit?usp=sharing). 

![1](https://user-images.githubusercontent.com/5697474/27189087-e822e948-51b5-11e7-9733-6d572a022d48.png)

**Comment by danielryne** [comment]
Working on draft of these here: https://docs.google.com/document/d/1bNqjBKuFQ7xDFdV5FSavNSwFjybPT49zhds21zZhJmg/edit?usp=sharing

**Comment by danielryne** [comment]
Ok, below are the Budget Party talking points and email. @mateoclarke and @VictoriaODell these are ready to be reviewed by you and ATA for feedback and revisions. Once they've been reviewed, we'll be ready to send them to set up meetings with council members. There are a few pending questions I have for this process: 

- What's left to be updated on the app right now and what is the timeline for those updates? 
- How quickly could it be updated with 2017-2018 budget projections? 
- How often could we provide council members with data from their districts? (once a week, upon request, etc)

PS. I won't be at the next hack Saturday on July 1st, as I'll be traveling for a bit. But I'm happy to circle about this at the civi tech meeting next week and/or set up some other time to chat about this. Let me know! 

Budget Party Talking Points [[WIP HERE](https://docs.google.com/document/d/1bNqjBKuFQ7xDFdV5FSavNSwFjybPT49zhds21zZhJmg/edit?usp=sharing)]

Budget Party Email to Council Members [[WIP HERE](https://docs.google.com/document/d/1N4JKGO_uXrRscWyWkOyUaMCUTsh4fKJIeUVXtMBTFls/edit?usp=sharing)]

Good Morning Council Member [_last name_],
 
My name is [_name_] and I’d like to request a brief meeting with you to discuss Austin Budget Party and how you can use it to get feedback from residents about the upcoming budget. Do you have half an hour available in the next two weeks that I may be able to discuss this with you and your staff?
 
Austin Budget Party is a free, local, open-source tool that helps residents understand the city budget by allowing them to shape their own general fund budget. It also allows you to collect feedback about the budget from residents in your district, and is available in English and Spanish. 
 
The [tool](https://atx.budgetsimulator.com/) that the city currently uses to collect feedback stops taking accepting feedback after July 15th, which is likely well before you’ll want to engage with your constituents about budget priorities.  Moreover, this platform was built by a private firm who created a one-size-fits-all tool for communities, not specifically for Austin. 

By comparison, Austin Budget Party was developed by local educators, developers, and designers from AISD, Open Austin and the Austin Monitor. I’d love to talk to you in more detail about this great community resource and how we can make it work for you!
 
Please let me know when you might be available. I'm looking forward to speaking with you and your staff! 
 
Best, 
 
[_name_]
[_title_], Open Austin
Resident, District [_#_]

**Comment by VictoriaODell** [comment]
Hey @danielryne! Sorry for the late reply. 

Everything you put together looks great. As far as your questions go this is what I have: 

**What's left to be updated on the app right now and what is the timeline for those updates?**
We have June Milestones documented here: 
https://github.com/open-austin/budgetparty/milestone/6

Working to clean those up and move stuff over to July when appropriate. 

**How quickly could it be updated with 2017-2018 budget projections?**
Uh, not sure about this one. I think this was something @graceatkins and @mateoclarke may have talked about. 

**How often could we provide council members with data from their districts? (once a week, upon request, etc)**

Right now we can say "upon request". I think for this we need to understand what data the council members would like to see and how often. We have all the data stored right now but we can create an admin side based on their needs to pull the data. This is something we can potentially ask them at our meetings. 

We should get these emails sent out soon though, yeah?

**Comment by danielryne** [comment]
@VictoriaODell thanks for looking this over and sending updates. I just updated the talking points to reflect that council members will be able to request anonymized feedback data by request, per your suggestion.

And I totally agree, we should start reaching out soon. @mateoclarke and @VictoriaODell - Do you want to start doing that this week? As in send the email and do a follow up call to the office?

Lets track our contact and outreach  [here](https://github.com/open-austin/budgetparty/issues/172).

**Comment by VictoriaODell** [comment]
Closing this since we have our talking points and are tracking meetings in issue #172
