### ISSUE TITLE
Budget Party Birthday Party

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/budgetparty#170]
Budget Party turns :one: on 6/30

- Start planning
  - venue (a bar?)
  - outreach
  - how to get ppl to submit their budget?

**Comment by mateoclarke** [comment]
Date to be aware of for Budget Party Game Night.

> Right now we are shooting for **Wed, August 9 from 6:30 - 8:30 pm**. We are still in the very early stages of scheduling this event - but we just wanted to make sure this date makes the most sense for everyone. 
> - Kasey Corpus from Austin Monitor/Glasshouse

**Comment by VictoriaODell** [comment]
Followed up to that ^^^ email suggesting we make the game night our party night too and I'd help with coordinating.  

I'm going to move this milestone to July since that's when we'll be doing most of the coordinating and planning for August. If we get a no, I hope not!, we can shoot for EOM July event and I can follow up with a guy that invited us to use his bar, maybe? or explore other options.

**Comment by mateoclarke** [comment]
There is an active thread in Slack #budgetparty about making this event have a remote videoconferencing element. Something we should discuss when we meet with Glasshouse Team IRL.

https://open-austin.slack.com/archives/C1NC5QDEW/p1498873140317964

**Comment by VictoriaODell** [comment]
Whoop. Need to get better at updating the issues. 
@mateoclarke have you heard back on rubric stuff or did I miss anything? Should we follow up with GH and AM? I got an email from Kasey about Oasis. I sent an email to the contact there and am waiting to hear back. I don't think an event page is up yet.

**Comment by mateoclarke** [comment]
No, I haven't heard about the rubric for the Budget Party game night. Kasey emailed me about logos and images. But she ended up using the wrong Open Austin logo she found online.
https://www.eventbrite.com/e/budget-party-tickets-36695300632

**Comment by VictoriaODell** [comment]
🙌🏼
https://medium.com/@glasshouse/budget-party-game-night-wrap-up-b359cf36108b
