### ISSUE TITLE
[July 9] CoA GigaTECH App competition submission deadline

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/budgetparty#173]
https://herox.com/GigaTECHSATX/updates

**Comment by VictoriaODell** [comment]
@mateoclarke you think we should do anything with this?

**Comment by mateoclarke** [comment]
I think you should totally apply! Given what we've learned about the low application rate, I know they are desperate for applications. There is a lot of money available. And it would give the product direct visibility at the City. 

But, I would have to stay out of the application process and could not be a beneficiary of any of the funds as an employee of the CoA starting in Aug.

So strong yes, but sorry I can't help.

**Comment by VictoriaODell** [comment]
FWIW They extended the deadline to the 15th? I think. I don't think it's good for me to take on another thing, especially with your decreased involvement @mateoclarke.

Maybe next year.
