### ISSUE TITLE
rounding not enough and too much in hte wrong place

### ISSUE THREAD

**Issue by durs125** [open-austin/budgetparty#177]
The change in the budget is rounded to the nearest percent. It will say no change if the change was only 0.4% in the end screen. I think rounding is not appropriate in this case. I think we need 1 decimal space.

For some reason, after hitting -.1 three times, it reads -.30000000004. In several other cases it also has over 5 decimal spaces.

**Comment by mateoclarke** [comment]
@durs125 Can you share a screen shoot and url of where this happens? That will make it easier to reproduce.

**Comment by VictoriaODell** [comment]
I think there are 2 issues here so I'm going to break these out. 

 1.) Here is one, where the decimal place goes over too much. When you're in the individual department services pages and you increase or decrease the decimal places, you occasionally get a large number shown below. 

![image](https://user-images.githubusercontent.com/10767430/27241879-227fcc60-52a0-11e7-860f-a0eaf9edb938.png)

We would like there to only be 2 decimal places and the number be rounded.

**Comment by VictoriaODell** [comment]
2)  I think this screenshot explains what David was referencing for the first point. 
![image](https://user-images.githubusercontent.com/10767430/27242030-d4146ba2-52a0-11e7-840a-7b3d9e351537.png)

**Comment by durs125** [comment]
Yes, Great example

**Comment by smonami** [comment]
Sorry for the multiple commits. This 2 parts issue has been fixed.
Also, please let me know if you need a separate pull request.
