### ISSUE TITLE
Formatting numbers

### ISSUE THREAD

**Issue by acabunoc** [open-austin/budgetparty#182]
The numbers are hard to understand without commas / dollar signs. Can they be formatted to be easier to read?

e.g. 
32433476 => $32,433,476

**Comment by acabunoc** [comment]
This might just be the web version:
<img width="512" alt="screen shot 2017-06-17 at 4 40 03 pm" src="https://user-images.githubusercontent.com/617994/27256180-a9601d12-537b-11e7-950c-58f4a353f9df.png">

**Comment by mateoclarke** [comment]
What browser are you using? I think the formatting library we are using, Format.js, requires a polyfill for Safari that we need to implement.

**Comment by acabunoc** [comment]
Firefox Dev Edition - but I tried out a bunch of browsers and it's the same in Chrome, Firefox (regular) and Safari.

MacOS Sierra 10.12.5
