### ISSUE TITLE
Help Fill in Final Fund Report for Ashley

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/budgetparty#187]
https://docs.google.com/document/d/1BAWXJa0NGi3ZO9k4knkbJXglavK-Lszh6MUEcIaUH-s/edit?usp=sharing

**Comment by VictoriaODell** [comment]
I added a couple things in Purple. I want to go back in and fill in some more details though.

**Comment by VictoriaODell** [comment]
@mateoclarke do you know if Ashley has seen all we added? Still, needs to be cleaned. We should follow up though.

**Comment by mateoclarke** [comment]
[FINAL Budget Party Gigabit Community Fund Final Report.docx](https://github.com/open-austin/budgetparty/files/1165988/FINAL.Budget.Party.Gigabit.Community.Fund.Final.Report.docx)
