### ISSUE TITLE
Open Savannah question

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/budgetparty#217]
> Hi 👋! We noticed in ‘app/src/data/departments.js’ that there appears to be conditional scenarios for things cutting expenses might trigger — but don’t see the JS that triggers the scenarios, and it’s not in current Austin deployment. Ideas? -💜fromGA

https://twitter.com/opensavannah/status/1040627192974200833

**Comment by mateoclarke** [comment]
cc/ @opensavannah 👋

**Comment by mateoclarke** [comment]
If you look at the [services data file](https://github.com/open-austin/budgetparty/blob/master/app/src/data/services.js#L14), each Service object has an array of integers that represent the `deptId` for the departments within a Service bucket. 

Services are intended to be a grouping of departments that have similar goals. Ex: Public Safety being an umbrella for EMS, Police, Fire & Muni Court.

**Comment by mateoclarke** [comment]
Oh derp, that didn't answer your question at all @opensavannah...

So, yeah in the original version of the app, we had what we were calling tradeoffs. 
https://github.com/open-austin/budgetparty/blob/master/app/src/data/departments.js#L20

We had intended for the summary page at the end of the game to give you a visual of the effect of your changes to the budget. We never got to implementing this feature for no good reason other than deadlines and resources.

Now, two years on, those figures might not be accurate and we have prioritized other aspects of the project mainly to facilitate judging the game nights we host with local city council members.

**Comment by carlvlewis** [comment]
Okay, that’s what we kind of assumed given there was nothing that data was being used for! We’d very much like to add this feature as you described it. 

While we’ll be using this as an educational tool throughout the year, the City of Savannah will be specifically using it to gauge resident input and feedback. Will add in the scenarios we have and see what we can do as far as stronger visual cues and warnings about the trade offs faced for certain cuts.
