### ISSUE TITLE
Design assets

### ISSUE THREAD

**Issue by brainnews** [open-austin/budgetparty#26]
Just starting a new issue for various design assets and handoff.

Services icons
- [x] Public safety
- [x] Development
- [x] Infrastructure & transport
- [x] Community services

Tab bar icons
- [x] Home
- [x] Revenue
- [x] Services
- [x] Report

Misc icons
- [x] Up arrow
- [x] Down arrow
- [x] Save & Submit
- [x] Your Budget

**Comment by brainnews** [comment]
@VictoriaODell here are some up and down arrows for you



[arrows.zip](https://github.com/open-austin/hack-the-budget/files/405090/arrows.zip)

**Comment by VictoriaODell** [comment]
Thanks! 
Bonus points if we could get 2 more to make the reports page a bit more snazzy 
<img width="330" alt="screen shot 2016-08-06 at 12 42 04 pm" src="https://cloud.githubusercontent.com/assets/10767430/17458338/3c1a8ff8-5bd3-11e6-9a59-a3e3f835b341.png">
<img width="360" alt="screen shot 2016-08-06 at 12 41 58 pm" src="https://cloud.githubusercontent.com/assets/10767430/17458343/4c748142-5bd3-11e6-8181-fe8e6f863fe0.png">

**Comment by brainnews** [comment]
@VictoriaODell Services icons for ya
[servicesSVGs.zip](https://github.com/open-austin/hack-the-budget/files/405141/servicesSVGs.zip)

**Comment by brainnews** [comment]
@VictoriaODell here are a couple icons for "Your Budget" and "Save & Submit"
[Archive.zip](https://github.com/open-austin/hack-the-budget/files/405798/Archive.zip)

**Comment by VictoriaODell** [comment]
@brainnews You're a Boss!

**Comment by VictoriaODell** [comment]
[Icons.zip](https://github.com/open-austin/hack-the-budget/files/416373/Icons.zip)

@mateoclarke

**Comment by brainnews** [comment]
here's the Budget Party logo SVG
[logo.svg.zip](https://github.com/open-austin/budgetparty/files/420611/logo.svg.zip)

**Comment by VictoriaODell** [comment]
Good here
