### ISSUE TITLE
Document how this project is different/better than Dollars & Sense

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/budgetparty#4]
- Inclusive to renters
  - home value isn't value isn't the first question asked
- Friendlier language & interface
  - we want this to be fun, not scary
- Mobile first design
- Community built and maintained
  - built and designed by local folks
  - built with Austin's in mind, not a blanket platform for any budgeting process.
- More realistically reflect the impact and tradeoffs

**Comment by graceatkins** [comment]
If you want a more longform version of this I can write it, but I think you've covered this pretty well!

**Comment by mateoclarke** [comment]
Expanded in #168
