### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/budgetparty#44]
need a lil baby image for browser tabs

**Comment by VictoriaODell** [comment]
Here is a bunch. Do these work? It's the little home icon. 

[Buildabudget_favicon.ico.zip](https://github.com/open-austin/buildabudget/files/416701/Buildabudget_favicon.ico.zip)

**Comment by mateoclarke** [comment]
This will work!

**Comment by mateoclarke** [comment]
https://github.com/open-austin/budgetparty/commit/c67d0a8220ff885fc390ff4039fca2774973a1a2
