### ISSUE TITLE
active state on Bottom nav Buttons

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/budgetparty#45]
we should give the user an indication of what page they are on.

**Comment by VictoriaODell** [comment]
I tried to show that some in the comp some~

But I think I would flip it. So blue would indicates the page you're on and grey indicates the other pages. Twitter and FB mobile have a similar patter. 

<img width="309" alt="screen shot 2016-08-13 at 12 54 58 pm" src="https://cloud.githubusercontent.com/assets/10767430/17644769/3f7df914-6155-11e6-9989-7cc85f555eb0.png">

**Comment by VictoriaODell** [comment]
This ui is not relevant for our current discussions.
