### ISSUE TITLE
Design feedback

### ISSUE THREAD

**Issue by thedonquixotic** [open-austin/budgetparty#67]
Really great stuff, I'm impressed. Looks solid, and it's nice and fast. Some thoughts:
- way too much needless information. Is there a reason the user _needs_ to know the exact number of civil servants employed by the budget? Onboarding page is like so many other civic websites, over saturated with text. That same info can be gotten across more concisely and more visually. 
- So the bottom bar is basically preceded through sequentially. Some kind of signifier for which one you are would be good. Additionally as it is basically sequential, some kind of numbering or sequence signifier would be good. Doesn't have to be numbers, could be a range of colors, but something to help indicated passage over time. 
- Love the illustrations on the services main page. Really smart. Actually would like to see this throughout the entire app more. This would help bring personality and I think help differentiate the groupings better. 
- Nice job separating the different sub categories into cards, but I feel they need something slightly more. Maybe a shadow to help them stick off the page (like the card system in Material Design https://material.google.com/components/cards.html )or something like that. The illustrations would also help as I said. 
- current buttons for increasing or decreasing the budget aren't bad, but I think they need to have more directionality to them. Doesn't have to be arrows, could also be something like a half circle shape or something else like that. It also needs an active click state so that when you click you know that you clicked it, not just that you see the numbers go up. More feed back is good. Also the severity of the increment should be indicated not only through the numbers but color. I would think that having a solid button color for the 1% and a ghost color button for the .1% would work, or a gradation of color (light red versus deep red, yellowish green versus bluish green)
- More interactivity to the visualizations would be a nice touch. Being able to see an increasing bar graph or a growing circle, really anything besides just numbers would make a big difference for usability. 
- I feel like the margin underneath "spending" is a little too large. It has a 10px margin on top and bottom, but since Spending is a headline for what goes under it, the amount of money, it should be more like 10px on top, and 2-5px on bottom, so that those two are more visually grouped. This general problem actually pops up in several other places, like "Your Budget" and a couple of other titles. 

Looks really slick and works fast though! I like it. Very cool.

**Comment by VictoriaODell** [comment]
Sweet! Thanks for the nice write up on feeback @thedonquixotic!
We'll be having a debrief session after we collect more user survey's from the event and we'll start taking some next steps from there. 

I invited you to the #Hackthebudget channel on slack so you can stay up to date. :)

**Comment by VictoriaODell** [comment]
I'm incorporating what was posted here into one issue at #66
