### ISSUE TITLE
Updated department numbers

### ISSUE THREAD

**Issue by graceatkins** [open-austin/budgetparty#68]
[https://docs.google.com/spreadsheets/d/1MnpxMPpX4QIvW4INpu5ATMZfMvtmCiolJc0FKKL3TJE/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1MnpxMPpX4QIvW4INpu5ATMZfMvtmCiolJc0FKKL3TJE/edit?usp=sharing)

**Comment by mateoclarke** [comment]
Nice, thanks for sharing this @graceatkins. Just now seeing it but will try to get the numbers updated before the event Saturday
