### ISSUE TITLE
Service Card UI Updates

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/budgetparty#70]
# We want to Update our Service cards
These are the stories we want to support: 
- As a user, I want to understand quickly what each service section does so that I can understand where I am allocating money.
- As a user, I want to justify my budgets so that others can understand my decision and reasoning. 
- As a user, I want to know restraints on the budgets spending so that I can make a budget that is realistic and reasonable.  

I have them all bundled here but maybe we can break these up into separate issues? 

This is our current card UI. We want to optimize it. 
<img width="386" alt="screen shot 2017-02-04 at 2 07 08 pm" src="https://cloud.githubusercontent.com/assets/10767430/22621189/44084daa-eae3-11e6-98ca-842b41721403.png">

# We need to make sure the following is included in our new card ui. 
- [ ] Title of the card
- [ ] Description of service
- [ ] An element that shows that calls out somethings special about one particular cards. ie: restrictions for limitations in spending, reasons why the starting spending 
- [ ] An area to add comment on why the student altered the budget
- [ ] Read more (discussed flipping the card)

**Comment by brainnews** [comment]
@VictoriaODell can we close this? seems to be a duplicate of #73

**Comment by VictoriaODell** [comment]
Sounds good @brainnews
