### ISSUE TITLE
Individual Service Pages

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/budgetparty#73]
# Updated Service page UI
**NOTE:** The cards are still being updated in a separate issue. Current text is just filler. 

This breaks from our current version that has the cards as a long list and instead allows you to swipe through cards.  I cut down the text significantly. 

### Current
<img width="250" alt="screen shot 2017-02-05 at 11 42 59 pm" src="https://cloud.githubusercontent.com/assets/10767430/22635915/f6e72756-ebfc-11e6-9ea8-242dccadd005.png">

### Proposed
<img width="250" alt="screen shot 2017-02-05 at 11 42 19 pm" src="https://cloud.githubusercontent.com/assets/10767430/22635892/c969d3f0-ebfc-11e6-9fbc-5a21faefa841.png">

**Comment by mateoclarke** [comment]
I really, really like this! 

Let's make sure to add how a non-touch/desktop user would page through the cards. Would those dots on the bottom be enough of a visual cue?

**Comment by VictoriaODell** [comment]
I'll be sure to iterate on that desktop ui @mateoclarke. 
I've seen the dots on website sliders but they're usually accompanied by arrows. :)

**Comment by VictoriaODell** [comment]
I noticed that on the "community service" page we have the most amount of cards in the entire game, ~7. We should think of doing a progress bar instead of a dots at the bottom. That would change navigation to purely be by swiping + arrows on desktop

**Comment by brainnews** [comment]
Iterating on this a little bit tonight... After playing around with alternate designs, the original structure emerged as the way to go in my opinion. Still playing around with color, but here it is:

![card-ui-05](https://cloud.githubusercontent.com/assets/3944802/22768651/2afaa524-ee49-11e6-85f3-4e43e4f26ea0.png)

Some of the other concepts I was working with had more amounts to increase/decrease funding. See below for those explorations:

![card-ui-01](https://cloud.githubusercontent.com/assets/3944802/22768716/85f826fe-ee49-11e6-95d3-75f1960ad565.png)

![card-ui-02](https://cloud.githubusercontent.com/assets/3944802/22768717/85f8f1e2-ee49-11e6-8002-3ced0e4a5867.png)

![card-ui-03](https://cloud.githubusercontent.com/assets/3944802/22768718/85f9e804-ee49-11e6-8e8a-13bf16406c63.png)

**Comment by VictoriaODell** [comment]
Hey Miles. I think the first option is looking good.

**Comment by brainnews** [comment]
@VictoriaODell 

**Here's an updated individual service page.** This includes the new top nav that displays total funds available and total spending for the service currently being edited.

![service budget view](https://cloud.githubusercontent.com/assets/3944802/23589499/e943b9f0-0193-11e7-9515-9e7bb0a9a2da.png)

And here's the Service Overview page after you've completed all the service cards.

![service spending overview](https://cloud.githubusercontent.com/assets/3944802/23589514/3427a38c-0194-11e7-9e65-99a56abe3df5.png)
