### ISSUE TITLE
Service Page Overview

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/budgetparty#74]
# Updated Service Page Overview
The current navigation isn’t linear and doesn’t really push the narrative of the game forward. It suggests that all the steps are equal and not sequential. We want to explore using the Service overview page as the games main navigational page. 

### Current
<img width="250" alt="screen shot 2017-02-05 at 11 50 39 pm" src="https://cloud.githubusercontent.com/assets/10767430/22636028/ed070eb2-ebfd-11e6-9e1a-39037427683e.png">

**Comment by brainnews** [comment]
@VictoriaODell – Didn't get a chance to work on this tonight, but still love the idea

**Comment by brainnews** [comment]
@VictoriaODell 

Here's the new services overview page. I'm calling it the **services path view** now that it's more like a linear path (or at least that's what how we want people to go through it).

![path view](https://cloud.githubusercontent.com/assets/3944802/23589530/73ef21b6-0194-11e7-9b97-52d0a6cb4213.png)

**Comment by VictoriaODell** [comment]
This is implemented. We can open new issues from here.
