### ISSUE TITLE
Information Architecture Diagram 

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/budgetparty#79]
Here is the folder to the diagram original files and pdf: 
[https://drive.google.com/open?id=0BwKb2oghmQldSHdHZjc2SjQtOGM](https://drive.google.com/open?id=0BwKb2oghmQldSHdHZjc2SjQtOGM)

Here is the main diagram
<img width="808" alt="screen shot 2017-02-08 at 4 33 47 pm" src="https://cloud.githubusercontent.com/assets/10767430/22760525/72ee011e-ee1c-11e6-8971-84b1a734136a.png">

**Comment by VictoriaODell** [comment]
@brainnews above is the stuff I made. I worked on this before starting to wireframe since it helped give me a better idea of the direction we're going, what pieces we need, and how much info we're dealing with. 

When I was working on the department services I noticed that some departments have less cards than the other ones. Because of this I think it would be good to "lock" each service department until the budget for the prior service is complete and emphasize that they can always go back and change their answer on previous sections. 

**Ex of flow:** 
After you finish infrastructure & mobility you're taken back to the home page. "infrastructure and mobility" & "budget breakdown(working title)" will be shown in color to illustrate that you can still click them. "development" would now have an indication that you could click it and start budgeting. "community service" and "submit budget(working title)" will still be greyed out until "development" is complete.


I think this will help with the more linear narrative and also ease people into the game since the first section has the least amount of cards. I kind of think of the last section as getting to the harder part since there are a lot of services to keep in mind.

**Comment by brainnews** [comment]
@VictoriaODell 
This looks great and really helps nail down the structure. The "unlocking" of subsequent services feels right and makes it feel like a game in a good way. Like levels in candy crush. I think the kids will like it.

**Comment by VictoriaODell** [comment]
This is pretty much done. We can add it to the design documentation
