### ISSUE TITLE
Hover states for things like buttons

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/budgetparty#87]
We talked about this at our last huddle but just wanted to remind.

**Comment by brainnews** [comment]
@mateoclarke here is the new sketch file. everything is in there except for one of the icons on the onboarding screen.


[budgetParty-v2.2.sketch.zip](https://github.com/open-austin/budgetparty/files/880263/budgetParty-v2.2.sketch.zip)

**Comment by VictoriaODell** [comment]
Blue button hover/ active state: #006285
green button hover/ active state: #4B830E

**Comment by cdikibo** [comment]
DONE
