### ISSUE TITLE
Change Global Fonts to Raleway

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/budgetparty#89]
@brainnews or @VictoriaODell, Can y'all list out the fonts we're using?

**Comment by brainnews** [comment]
Raleway throughout (its a google font)
[Archive.zip](https://github.com/open-austin/budgetparty/files/882213/Archive.zip)

**Comment by VictoriaODell** [comment]
Currently we are only using Medium and bold in our design

https://fonts.google.com/specimen/Raleway
