### ISSUE TITLE
Align all buttons

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/budgetparty#91]
![image](https://cloud.githubusercontent.com/assets/10767430/25559127/ce9608f0-2cfa-11e7-82c0-72508f1d1b2a.png)

There's a pattern in the design we need to implement. 
All the buttons should be 70px from the bottom.
Could do this with flexbox or position:absolute.

**Comment by DanBuda11** [comment]
Just pushed to branch "align-service-intro-buttons" & started pull request.
