### ISSUE TITLE
Make things look better for Desktop

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/budgetparty#95]
We could just do what we did on v0.

![image](https://cloud.githubusercontent.com/assets/5697474/25559516/7977e274-2d01-11e7-89ca-f8d7cccb89d1.png)

But there might be specific pages that should have a good layout for non-mobile screens.

**Comment by VictoriaODell** [comment]
<img width="627" alt="screen shot 2017-05-10 at 8 03 01 pm" src="https://cloud.githubusercontent.com/assets/10767430/25927452/bb02b666-35bb-11e7-8c5e-2e9e35fee9c4.png">
It would be nice to get something like the above.

**Comment by VictoriaODell** [comment]
Closing this for now.
