### ISSUE TITLE
Export Images/Icons as SVG

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/budgetparty#97]

**Comment by brainnews** [comment]
@mateoclarke I've exported the images from the onboarding pages. The "confetti" around each image is different, so I exported the confetti separately with a corresponding filename.

Do you also need the services icons as SVG?

[File Delivery.zip](https://github.com/open-austin/budgetparty/files/985344/File.Delivery.zip)

**Comment by VictoriaODell** [comment]
<img width="693" alt="screen shot 2017-05-10 at 8 48 37 pm" src="https://cloud.githubusercontent.com/assets/10767430/25928471/106b8a78-35c2-11e7-9568-eac9abb5c03c.png">

As Miles said, the confetti is different. We need help getting the icons updated and in the application 
These images are specifically for the "welcome" flow at the beginning of the application.
