### ISSUE TITLE
Copy Writing

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/budgetparty#98]
The CoA Open Performance page might be a good place for research:
https://data.austintexas.gov/stories/s/performance-atx/mfnw-2iaf

## Service Bucket Descriptions 
(~250 words)

-[ ] Development
- [x] Infrastructure & Mobility
- [x] Public Safety
- [x] Community Services
  > "The departments housed under community services provide services including providing environmental health services, animal services, and family health services, and managing the City’s libraries, parks, and affordable housing efforts."

## Department Short Descriptions
(~75 words)
- [x] Municipal Courts
- [x] Police
- [x] Fire
- [x] Emergency Management Services
- [x] Planning & Zoning
- [x] Development Services
- [x] Animal Services
- [x] Parks & Recreation
- [x] Public Libraries
- [x] Social Service Contracts
- [x] Health & Human Services
- [x] Neighborhood Housing & Community Development
- [x] Transportation Department
- [x] Public Works

## Department Longer Descriptions (Learn More)
(~250 words, Edit/Revise if necessary)
 - [ ] Municipal Courts 
    > Municipal court and Downtown Austin Community Court make up the judicial branch of the City of Austin local government. The court oversees cases of traffic, city ordinance, state code, and parking violations.
 - [ ] Police 
    > Officers do everything from enforcing the law, to preventing crime, investigating crime, reaching out to the community and writing reports
 - [ ] Fire 
    > The Austin Fire Department is committed to creating safer communities through prevention, preparedness and effective emergency response.
 - [ ] Emergency Management Services 
    > EMS provides emergency communication services, ground and air emergency ambulance response, standby support, and special rescue services to the community.
 - [ ] Planning & Zoning 
    > The Purpose of the Planning and Zoning Department is to provide planning, preservation and design services. PAZ is responsible for long range planning, current planning (including historic preservation, annexation, and zoning), urban design services, and updates of the Land Development Code. Current Projects underway: Imagine Austin, CodeNEXT, South Center Waterfront Initiative.
 - [ ] Development Services 
    > Development services oversees the operations of the "one-stop shop". The purpose of the One Stop Shop is to consolidate the process of land development permitting and assistance into a single location.
 - [ ] Animal Services 
    > The purpose of the Animal Services Office is to provide an array of animal control, health, and pet-owner services to the public in order to promote responsible pet ownership and humane treatment of animals. They provide food, water, shelter and veterinary care for lost or homeless animals. They enforce animal regulations including impoundment, quarantine and other rabies control services.
 - [ ] Parks & Recreation 
    > Parks and Recreation department is tasked with providing, protecting, and preserving the city’s park system.
 - [ ] Public Libraries 
    > Austin Public Libraries' mission is to provide easy access to books and information for all ages. The budget includes staffing and management of existing and planned library facilities.
 - [ ] Social Service Contracts 
    > The Social Services Contracts program includes funding for basic needs, behavioral health, child and youth services, HIV, homelessness, community planning efforts, and workforce development. We divided social service contracts from Health and Human Services Department to highlight the role these contracts play in the budget process.
 - [ ] Health & Human Services 
    > Mission is to prevent disease, and promote and protect the health and well-being of the community by providing services such as immunizations, food, shelter, and job assistance, health screenings , and overseeing the inspection and permitting of restaurants
 - [ ] Neighborhood Housing & Community Development 
    > The Neighborhood Housing & Community Development programs  include housing, small business assistance, renter assistance, and neighborhood and community revitalization.
 - [ ] Transportation Department 
    > In 2008, the City of Austin established the Austin Transportation Department to address the city’s sustained transportation and mobility needs. The department administers and oversees the city’s traffic and parking management programs and transportation planning efforts.
 - [ ] Public Works 
    > Public Works Department is tasked with the physical construction and maintenance of the City's infrastructure. The four primary service areas are 1) street and bridge maintenance and repair; 2) Design and implementation of capital improvement projects; 3) Neighborhood connectivity activities  (i.e. the planning and construction of pedestrian amenities and the construction of bicycle facilities); 4) Implementation of the child safety program including school zone improvement projects and school zone crossing guards.

**Comment by mateoclarke** [comment]
@VictoriaODell, this commit is related to this issue right?
https://github.com/open-austin/budgetparty/commit/0aae927e8c1ad177e3879dc399d41b6b9e15b20a

Still more work to do on it before we close?

**Comment by VictoriaODell** [comment]
@mateoclarke I got all the description updated but still want to go in and add line breaks to the full page descriptions. I can try to get that done EOD.

**Comment by VictoriaODell** [comment]
Working on this now.
